### ISSUE TITLE
Running into some errors when running the TFF for Image Classification and Text Generation co-lab notebook

### ISSUE THREAD

**Issue by solmazeradat-aridhia** [tensorflow/federated#2129]
Hi,

I am going through the material in the colab notebooks in [Federated Learning Workshop using TensorFlow Federated](https://events.withgoogle.com/demostutorials-workshop-on-federated-learning-and-analytics-2020/).

There are 3 errors in the notebook that am trying to understand why they are happening. This is the link to a copy of the colab I created [TFF for Image Classification and Text Generation](https://colab.research.google.com/drive/18Nn3SQVfc4QiZoNab3xr46g-T-kfAX97#scrollTo=NTUig7QmXavy&uniqifier=1).

There is the screen shots of the three errors: 

- ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spacy 2.2.4 requires tqdm<5.0.0,>=4.38.0, but you have tqdm 4.28.1 which is incompatible.
pymc3 3.11.4 requires cachetools>=4.2.1, but you have cachetools 3.1.1 which is incompatible.
panel 0.12.1 requires tqdm>=4.48.0, but you have tqdm 4.28.1 which is incompatible.
fbprophet 0.7.1 requires tqdm>=4.36.1, but you have tqdm 4.28.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.

- AttributeError: module 'tensorflow_federated.python.simulation' has no attribute 'ClientData'

![image](https://user-images.githubusercontent.com/91956839/141482982-6576db88-169c-4853-9b6a-83d1ce46d167.png)

- AttributeError: module 'tensorflow_federated.python.learning' has no attribute 'assign_weights_to_keras_model'

![image](https://user-images.githubusercontent.com/91956839/141483097-be4b0e5c-e291-4bf7-abb5-e1f64d88802e.png)

Any help in understanding or resolving these errors would be greatly appreciated. 

Many thanks,
Solmaz

**Comment by NeoDH** [comment]
for this issue 
> AttributeError: module 'tensorflow_federated.python.learning' has no attribute 'assign_weights_to_keras_model'
I guess this function is depreciated in the current version. I replaced it with 
`state.model.assign_weights_to(keras_model)`
in my own experiment and it could work.
[https://tensorflow.google.cn/federated/api_docs/python/tff/learning/ModelWeights](Reference)

**Comment by zcharles8** [comment]
Hi all. Since those tutorials were written (> 1 year ago), there have been a number of updates to TFF, including:

*   `tff.simulation.ClientData` has been moved to `tff.simulation.datasets.ClientData`
*   `tff.learning.assign_weights_to_keras_model` has been deprecated in favor of `tff.learning.Model.assign_weights_to`.

We keep the official TFF tutorials [link](https://www.tensorflow.org/federated/tutorials/tutorials_overview) up to date as the API changes. Please see the [image classification](https://www.tensorflow.org/federated/tutorials/federated_learning_for_image_classification) and [text generation](https://www.tensorflow.org/federated/tutorials/federated_learning_for_text_generation) tutorials for the full details.

**Comment by solmazeradat-aridhia** [comment]
Thanks you so much @NeoDH and @zcharles8 for sharing the information above. Will try out your suggestions.
