### ISSUE TITLE
What is the role of 'clipped_count_stddev' in differentially private gaussian_adaptive aggregator?

### ISSUE THREAD

**Issue by UserFindingSelf** [tensorflow/federated#2211]
I was going through the documentation of [gaussian_adaptive aggregator](https://www.tensorflow.org/federated/api_docs/python/tff/aggregators/DifferentiallyPrivateFactory?version=nightly#gaussian_adaptive), and one of the function arguments is `clipped_count_stddev`. Description says that it is 
```
The stddev of the noise added to the clipped counts in the adaptive clipping algorithm
```
But I thought the standard deviation of Gaussian noise added is calculated as **'clipping_threshold * noise_multiplier'**, where clipping threshold is found adaptively and the noise multiplier is fixed. 

What am I missing? Thank you!

**Comment by galenmandrew** [comment]
`clipped_count_stddev` is the standard deviation added to the count of clipped updates for private estimation of the quantile for adaptive clipping. It corresponds to \sigma_b in the paper https://arxiv.org/pdf/1905.03871.pdf. If you do not set this argument in `gaussian_adaptive`, it will default to the recommended settings from the paper as implemented in `adaptive_clip_noise_params`. This should work very well for almost all users.

**Comment by UserFindingSelf** [comment]
Thank you @galenmandrew! So if I understand it right, `sigma_b` is the standard deviation of noise used to estimate the _clipping threshold_ and noise multiplier `z_delta` is used to add the noise to the updates themselves. 

I have another question then. If `clipped_count_stddev` is by default = _**0.05 * clients_per_round**_, then won't this noise be higher for more clients_per_round? Unless it is normalized with respect to number of clients. 

I actually wanted to see the effect of count of clients participating in a round.

**Comment by galenmandrew** [comment]
Your first point is almost correct. The noise multiplier that you specify is the *effective noise multiplier* for DP accounting (z in the paper). Due to the need to account for privacy when estimating the clipping threshold, the actual amount of noise added to the updates (z_\Delta in the paper) will be very slightly (even negligibly) higher.

On the second point: yes the noise added to the sum of clipped counts will be higher for more clients per round, but note that it will be normalized by the `clients_per_round` so the noise on the average remains the same: 0.05. We find that 0.05 gives a reasonable amount of error in the estimation process while using a negligible fraction of the privacy budget.

**Comment by UserFindingSelf** [comment]
Thank you for clarifying! I have understood it now.
