### ISSUE TITLE
dataset_computation not implemented error

### ISSUE THREAD

**Issue by Crazynovatech** [tensorflow/federated#2659]
While trying to implement the python program working_with_client_data.ipynb provided in githhub, I am getting the below error as he function is not implemented. Can anyone help me when this will be available for public use? I was trying to check the program if it helps in the model training on the client device data.

def dataset_computation(self):
    raise NotImplementedError("b/162106885")

**Comment by jkr26** [comment]
Looking in our code, I think this implementation should be finished (that bug is [no longer referenced in TFF](https://github.com/tensorflow/federated/search?q=b%2F162106885)). This jibes with my recollection as well.

It might be that you're running an old version of TFF? Can you check you're on the 0.20.0 release, as I *believe* this should contain the appropriate implementations?

**Comment by Crazynovatech** [comment]
Apologies!! Updated the version to 0.20.0 and it works fine!!
