### ISSUE TITLE
tf.print not outputting anything in federated computation in multi-machine setup

### ISSUE THREAD

**Issue by ewenw** [tensorflow/federated#2888]
Hi, is there a way to output to std.out or a file from a client directly when running in a multi-machine setup?

For example:
```
@computations.federated_computation(FederatedType(tf.string, placements.CLIENTS))
def fed_print(x):
  tf.print(x)

federated_map(fed_print, client_messages)
```

Doesn't printout anything on the head or worker nodes.

**Comment by jkr26** [comment]
Doing something like this *is possible*, but the `tf.print` op must be captured in a TF computation. That is, something like the following should work:

```python
@tff.tf_computation(tf.string)
@tf.function
def print_and_return(x):
  # we get program order semantics here due to the tf.function,
  # which is why we use that as a second-decorator. Otherwise
  # we'd need to control-dep.
  tf.print(x)
  return x

@tff.federated_computation(tff.type_at_clients(tf.string))
def map_and_print(x):
  return tff.federated_map(print_and_return, x)
```

I'd share a colab, but I think they're all broken at the moment due to version mismatch (unless Colab has updated to Python 3.9). In general, TFF does not support the 'mixing' of TensorFlow and federated code; all TensorFlow code should be captured in TFF's `tf_computation` decorator. This was an early design choice in TFF, in order to help separate concerns--`federated_computation` decorators should usually contain logic which 'moves' tensors around--broadcasting, aggregating, etc.--or transforms them 'in groups'--mapping functions across the client or the server, for instance. Local logic should usually be expressed in one of TFF's local computation decorators, like `tf_computation` or the recently introduced `jax_computation`.
