### ISSUE TITLE
Can TFF be simulated in distributed machines within a LAN?

### ISSUE THREAD

**Issue by zhangxinqian** [tensorflow/federated#295]
Can TFF be simulated in distributed machines within a LAN?

**Comment by GFibrizo** [comment]
I'm interested about this too. 
I have been experimenting a little with federated learning and I developed a proof of concept for training a model through federated learning. In this PoC the server and the clients run each one, in a different docker container and they communicate via network.
I would like to code again this PoC, but this time using TFF. Is it possible to do that with the interfaces that TFF FL API offers? And with the FC API?
(I'm asking this here because I couldn't something that could clarify this to me in the documentation in the home page of the project. If there was and I missed it, sorry, my bad).
Thanks in advance!

**Comment by krzys-ostrowski** [comment]
Hello. Thank you for interest in contributing to TFF. We are just about to start working on setting up interfaces and components to enable high-performance simulations, and as a part of that, we'll provide guidelines for how to use and extend these interfaces. Thank you for your patience. Please stay tuned for updates.
