### ISSUE TITLE
PIP and Import not working in VS code for building a federated learning library

### ISSUE THREAD

**Issue by divya034** [tensorflow/federated#3090]
I intend to build a library (that can be imported by anyone)from my google collab notebook but when I convert this code into python and try to run it in VS code it is not working.

I am trying to make a library by using VS code, is there any other way to build that library from ipynb file ?

the starting part of the code looks like this:
```
# last known working versions:

# keras-nightly==2.10.0.dev2022051807
# tensorflow==2.8.0
# tensorflow-federated-nightly==0.19.0.dev20220218
# tb-nightly==2.10.0a20220508

!pip uninstall --yes tensorboard tb-nightly

!pip install --quiet keras-nightly==2.10.0.dev2022051807
!pip install --quiet tensorflow
!pip install --quiet --upgrade tensorflow-federated-nightly==0.19.0.dev20220218
!pip install --quiet --upgrade nest-asyncio
!pip install --quiet --upgrade tb-nightly==2.10.0a20220508

import nest_asyncio
nest_asyncio.apply()
```

Then:

```
import attr
import abc

import numpy as np
import tensorflow as tf
import tensorflow_federated as tff

import tensorflow_datasets as tfds
import collections
from tensorflow.keras import layers
from collections import OrderedDict

np.random.seed(0)

tff.federated_computation(lambda: 'Hello, World!')()
```

**The error says: ModuleNotFoundError: No module named 'tensorflow_federated' (in ipynb file in VS code)

If i convert this to python file, none of the import or pip or tensorflow statements work in VS code

Can someone please help me create a library for this code I wrote in google colab**

**Comment by michaelreneer** [comment]
If I understand you correctly, you are trying to create a Python package that depends on `tensorflow-federated` and you are starting in Google colab to prototype some functionality which you then want to iterate on in VS code locally. This should be possible!

1. You should be able to export the python out of the Google colab at the command line, or you can just copy-paste it.
2. Instructions for building a Python package can be found https://packaging.python.org/en/latest/tutorials/packaging-projects/.
3. It seems like the errors you are getting is because you did not setup the Python environment in VS code approprately.

I am going to close this bug, because it does not look like an issue with TFF. Please reopen if that is not the case.
