### ISSUE TITLE
When trying to load the libraries in google colab and kaggle it is not getting load correctly.

### ISSUE THREAD

**Issue by mahii6991** [tensorflow/federated#3106]
This is the error it is showing.

![image](https://user-images.githubusercontent.com/61599939/180654888-dbc1d25e-ffc0-4720-b8a6-963324c792de.png)

Though I have tried loading the kernel multiple times, but still I am getting the same error.

**Comment by ptn77** [comment]
Did you get this resolved? I'm also getting similar errors. Thanks!

**Comment by PlatypusProgrammer** [comment]
I am also not able to execute the example notebooks.
E.g.: https://www.tensorflow.org/federated/tutorials/federated_learning_for_image_classification
Pip is not able to install the packages.

![Capture](https://user-images.githubusercontent.com/99875548/183920105-c82b8d93-983b-44ba-9ec5-dcb3f3d1d850.PNG)

**Comment by mahii6991** [comment]
yes, for me it is not resolved till now !!!

**Comment by michaelreneer** [comment]
@mahii6991 

It is somewhat expected (though unfortunate) that you are getting error in Google colab. The reason for this is because the default runtime that you are executing the notebook in contains python packages that are not compatible with `tensorflow-federated`. However, these errors should not prevent you from continuing to execute the cells in the notebook.

1. Do you get an error when you run the next cell in the notebook?
2. If you run `!pip freeze` after running `!pip install --quiet --upgrade tensorflow-federated`, do you see that `tensorflow-federated` is installed?

If you want to get rid of the errors, then you can:

1. Create your own runtime or connect to an existing runtime that contains a set of packages that does not conflict with `tensorflow-federated`.
2. You could uninstall all the python packages that conflict with `tensorflow-federated` before trying to install `tensorflow-federated`, `!pip uninstall --yes <foo>`.
3. You could try to uninstall all the python packages before trying to install `tensorflow-federated`, `!pip freeze | xargs uninstall --yes`.
4. You could redirect the errors to `2>/dev/null`.
