### ISSUE TITLE
AttributeError: module 'tensorflow_federated.python.core.backends.native' has no attribute 'set_local_python_execution_context'

### ISSUE THREAD

**Issue by ahmedsohair** [tensorflow/federated#3189]
I'm getting the error " tff.backends.native.set_local_python_execution_context( AttributeError: module 'tensorflow_federated.python.core.backends.native' has no attribute 'set_local_python_execution_context' " while trying to run emnist_fedavg_main.py

I'm using TFF version 0.32.0

**Comment by ahmedsohair** [comment]
I'm using TFF version 0.32.0

**Comment by michaelreneer** [comment]
Hi @ahmedsohair It looks like that symbol is present in v0.32.0 https://github.com/tensorflow/federated/blob/v0.32.0/tensorflow_federated/python/core/backends/native/__init__.py. I suspect that you might be missing other symbols too? can you try running `dir(tff.backends.native)` to investigate? Also are you running this locally after building TFF? Are you creating a virtual env and pip installing TFF?

My guess is that you are not installing a virtual env and not building TFF and instead you are trying to run the binary and Python is not failing to import TFF because your current working directory contains the tff repo with a "tensorflow_federated" package?
