### ISSUE TITLE
import tensorflow_federated as tff in google colab

### ISSUE THREAD

**Issue by Sanmaryjoseph** [tensorflow/federated#3643]
I am getting dependency issues when i tried using the above statement.
How to fix this error ?

**Comment by lndulgence** [comment]
You need to be more specific with respect to what the problem is, and post some of the error messages you're getting, if possible. In any case, this seems related to #3428 , as google colab uses python 3.7, not 3.9 at the moment. I suggest you take a look at the linked issue and see if it works for you.

**Comment by abirbenzaamia** [comment]
Actually tensorflow-federated is not compatible with python3.7, try to change the version to python3.9 in colab and it will work.

**Comment by zcharles8** [comment]
The `0.52.0` release of TFF (https://github.com/tensorflow/federated/releases/tag/v0.52.0) was just pushed to PyPi (https://pypi.org/project/tensorflow-federated/0.52.0/) should fix this issue. Please re-open the issue (with details on your pip environment, among other things) if you continue to experience this issue.
