### ISSUE TITLE
BUILD instructions out of date

### ISSUE THREAD

**Issue by doug-leith** [tensorflow/federated#3730]
The build instructions:

python3.9 -m venv "venv"
source "venv/bin/activate"
pip install --upgrade "pip"

use python3.9 but tensorflow-federated now requires python3.10.  

suggested fix: update instructions to use python3.10, and make the dependency on that clearer (also I think it'd be helpful to make the dependency on tensorflow version clear too).  better still, can the build instructions be modified to remove this hard-wired dependency in the commands used?

**Comment by zcharles8** [comment]
Thanks for the report. As far as I know, TFF still works with python3.9, so more details here would be useful. Could you fill in the information in our bug template (reproduced below). Additionally, can you clarify where you are seeing that python3.10 is required?

Last, the TF version information can be found in the `requirements` file (https://github.com/tensorflow/federated/blob/main/requirements.txt#L46). Any suggestions for how to better surface this information are appreciated.

---

**Describe the bug**
A clear and concise description of what the bug is. It is often helpful to
provide a link to a [colab](https://colab.research.google.com/) notebook that
reproduces the bug.

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
* Python package versions (e.g., TensorFlow Federated, TensorFlow):
* Python version:
* Bazel version (if building from source):
* CUDA/cuDNN version:
* What TensorFlow Federated execution stack are you using?

Note: You can collect the Python package information by running `pip3 freeze`
from the command line and most of the other information can be collected using
TensorFlows environment capture
[script](https://github.com/tensorflow/tensorflow/blob/master/tools/tf_env_collect.sh).

**Expected behavior**
A clear and concise description of what you expected to happen.

**Additional context**
Add any other context about the problem here.

**Comment by michaelreneer** [comment]
I believe https://github.com/tensorflow/federated/commit/8cb2bfad94fb5417ac04ce606ab2dd643087ad49 should fix this issue.
