### ISSUE TITLE
Why the evaluation on test using the sample_clients from training in the EMNIST tutorial?

### ISSUE THREAD

**Issue by jinhw1989** [tensorflow/federated#534]
I went through the EMNIST tutorial https://www.tensorflow.org/federated/tutorials/federated_learning_for_image_classification
, but found the problem in the evaluation section:

> __federated_test_data__ = make_federated_data(emnist_test, sample_clients)
> len(federated_test_data), federated_test_data[0]

The `federated_test_data` is generated from `sample_clients`, while the `sample_clients` comes from the training set
>#@test {"output": "ignore"}
NUM_CLIENTS = 3
__sample_clients__ = __emnist_train__.client_ids[0:NUM_CLIENTS]
federated_train_data = make_federated_data(emnist_train, sample_clients)
len(federated_train_data), federated_train_data[0]

Why not take it as 
```python
sample_clients_test = emnist_test.client_ids[0:NUM_CLIENTS]
federated_test_data = make_federated_data(emnist_test, sample_clients_test)
evaluation(state.model, federated_test_data)
```

Is that an error or can someone explain it?

**Comment by ZacharyGarrett** [comment]
This is by design; from the [documentation](https://www.tensorflow.org/federated/api_docs/python/tff/simulation/datasets/emnist/load_data) for `tff.simulation.datasets.emnist.load_data()`:

> Rather than holding out specific users, each user's examples are split across train and test so that all users have at least one example in train and one example in test. Writers that had less than 2 examples are excluded from the data set.

So the while the evaluation is processing the same clients, it is not processing the same examples.

As you suggest, holding out entire *clients* (instead of *examples*) definitely seems reasonable and is an alternative way to evaluate the quality of a model.
