### ISSUE TITLE
The error "ImportError: cannot import name 'computation_pb2'" still appears

### ISSUE THREAD

**Issue by RansSelected** [tensorflow/federated#610]
Hi!

The error "ImportError: cannot import name 'computation_pb2'" still appears when running
python -c "import tensorflow_federated as tff; print(tff.federated_computation(lambda: 'Hello World')())"

even after installation of TF Federated via Bazel. At the same time running
bazel test tensorflow_federated/python/examples/mnist:models_test
performs well, with no error.

Specs:
MacOS Sierra 10.12
Python 3.6
PyCharm CE 2019 IDE
Conda env

**Comment by ZacharyGarrett** [comment]
One hypothesis is that this error is seen when running `python -c "import tensorflow_federated as tff; print(tff.federated_computation(lambda: 'Hello World')())"` in the root directory of the git repository. This might result in `import tensorflow_federated` importing from `./tensorflow_federated/__init__.py` instead of the pip package.

Could you verify whether the "hello world" test works from a directly that does not have a `tensorflow_federated` sub-directory?

**Comment by bsabri** [comment]
I had the same issue. When I changed the directory. The "Hello world" worked! Thanks

**Comment by ZacharyGarrett** [comment]
Thanks for confirming @bsabri!
