### ISSUE TITLE
How to assign different training functions to different  clients?

### ISSUE THREAD

**Issue by HaiQW** [tensorflow/federated#760]
The  low-level function ` tff.federated_mean(tff.federated_map(fn, data))` assigns the same training function to all of the clients. Are there any way to assign different training functions to the clients?

**Comment by ZacharyGarrett** [comment]
Hi @HaiQW, this sounds more like a question about how to use TFF that could be better asked on [StackOverflow using the [tensorflow-federated] tag](https://stackoverflow.com/questions/tagged/tensorflow-federated) rather than an issue with the TFF codebase that can be resolved. Could you please ask your question there?
