### ISSUE TITLE
How does tff allocate processes or threads?

### ISSUE THREAD

**Issue by phalangee** [tensorflow/federated#776]
How does tff allocate processes or threads in the code ?If it is parallel, then there will definitely be code to create a process or thread. I looked at the code but didn't see the content, so I was confused how it distributed the data to different clients and trained independently.
Thank you very much

**Comment by ZacharyGarrett** [comment]
This question is may be better suited fro the `tensorflow-federated` tag on StackOverflow (https://stackoverflow.com/questions/tagged/tensorflow-federated); TFF uses GitHub issues for bugs and feature requests, and StackOverflow for questions & answers.

 The default simulation execution does not run multi-threaded; this executor is called the _reference executor_ ([code link](https://github.com/tensorflow/federated/blob/8c904235dbf00431a95b5b1c64017aecf14517e6/tensorflow_federated/python/core/impl/reference_executor.py#L552)) which is very straight forward and less performant by design; it is optimizing for _correctness_. This processes each client serially on the local machine.

There is also a _concurrent executor_ ([code link](https://github.com/tensorflow/federated/blob/8c904235dbf00431a95b5b1c64017aecf14517e6/tensorflow_federated/python/core/impl/concurrent_executor.py#L26)) which runs using Python's `asyncio` event loop. Most users will want to create an executor stack with `tff.framework.create_local_executor()`, there are example usages in [this tutorial](https://github.com/tensorflow/federated/blob/v0.10.1/docs/tutorials/simulations.ipynb). This can process multiple clients in parallel on a single machine.

Good progress has been made on a _remote executor_, which will allowing running simulations in a distributed fashion on multiple machine; stay tuned.

Note: this is all for _simulating_ federated learning.
