### ISSUE TITLE
Does TFF framework not support encryption algorithms currently，such as SMC DP？

### ISSUE THREAD

**Issue by happy2019-k** [tensorflow/federated#778]
If tff framework not support encryption algorithms, how to prevent user data disclosure?@krzys-ostrowski @jkr26

**Comment by jkr26** [comment]
Hi @happy2019-k 

TFF is somewhat orthogonal to the actual encoding of data as it goes across a network; TFF right now is essentially geared towards *simulating* federated learning rather than deploying FL to real devices, and so it doesn't really make sense for TFF to be focused on encrypting data to go across the wire.

This is really the responsibility of the *deployment* framework for the federated learning system, rather than that of the language to specify the federated computations, which is how TFF views itself.
