### ISSUE TITLE
Model with multiple inputs of varying shape

### ISSUE THREAD

**Issue by aqibsaeed** [tensorflow/federated#785]
Is there an example of a tff model with multiple inputs that are not of same shape? I tried the following code snippet to create a tf.data object but it is not working as tf.data api doesn't allow stacking tensors of varying ranks. 

```
def map_fn(example):
  return {'x': [tf.reshape(example['pixels'], [-1]), 
      tf.reshape(np.zeros((32,32) ,dtype=np.float32), [-1])], 'y': example['label']}

def client_data(n):
  ds = source.create_tf_dataset_for_client(source.client_ids[n])
  return ds.repeat(10).map(map_fn).shuffle(500).batch(20)

source, _ = tff.simulation.datasets.emnist.load_data()
client_data(1)
```

this is the raised error: 

`ValueError: Value [<tf.Tensor 'Reshape:0' shape=(784,) dtype=float32>, <tf.Tensor 'Reshape_1:0' shape=(1024,) dtype=float32>] is not convertible to a tensor with dtype <dtype: 'float32'> and shape (2, None).`

This could also be useful:

```
def map_fn(example):
  return {"x": (tf.reshape(example['pixels'], [-1]), 
                np.zeros((32,32)).astype(np.float32)), 
          
          "y": [example['label']]}

def client_data(n):
  ds = source.create_tf_dataset_for_client(source.client_ids[n])
  return ds.repeat(1).map(map_fn).shuffle(500).batch(5)

source, _ = tff.simulation.datasets.emnist.load_data()
train_data = [client_data(n) for n in range(2)]
batch = tf.nest.map_structure(lambda x: x.numpy(), iter(train_data[0]).next())

def model_fn():
  finput = tf.keras.layers.Input((784,), name = "a")
  oinput = tf.keras.layers.Input((32,32), name = "b")

  ox = tf.keras.layers.Flatten()(oinput)
  concat = tf.keras.layers.Concatenate()([finput, ox])
  output = tf.keras.layers.Dense(10, tf.nn.softmax, 
                                 kernel_initializer='zeros')(concat)
  model = tf.keras.models.Model({"a": finput, "b": oinput}, output)
  model.compile(
      loss=tf.keras.losses.SparseCategoricalCrossentropy(),
      optimizer=tf.keras.optimizers.SGD(0.02),
      metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])
  return tff.learning.from_compiled_keras_model(model, batch)

trainer = tff.learning.build_federated_averaging_process(model_fn)
```
Error: 
```
ValueError: Shapes must be equal rank, but are 2 and 3
From merging shape 0 with other shapes. for 'Shape/packed' (op: 'Pack') 
with input shapes: [?,784], [?,32,32].
```

**Comment by ZacharyGarrett** [comment]
In the first example, the value for the `x` key in the `dict` is a `list` of tensors. I believe TensorFlow dataset is going to try and concatenate/stack these into a single tensor, but this will fail because they are not compatible shapes. This is fixed in the second code block by using a `tuple` instead of a `list` for the value of `x`.  This question is more of _how to use_ TensorFlow or TFF and would probably be best asked on StackOverflow so the community can benefit from the discussion even after this issue is closed. [[tensorflow-federated]](https://stackoverflow.com/questions/tagged/tensorflow) and [[tensorflow]](https://stackoverflow.com/questions/tagged/tensorflow) tags have been created for this purpose.

In the second example, it looks like there is an issue with [this line](https://github.com/tensorflow/federated/blob/547eeae6b65f6951504dfb49615a782306a6e097/tensorflow_federated/python/learning/keras_utils.py#L440) in TFF when multiple inputs have been specified. Probably this line needs to be replaced with something like `tf.shape(tf.nest.flatten(inputs)[0])`.

**Comment by aqibsaeed** [comment]
Thank you for prompt response. Do you think the issue mentioned in second example will be fixed anytime soon?

**Comment by ZacharyGarrett** [comment]
Yup, I'm hoping to have a PR merged today. Currently running through continuous integration tests.

**Comment by aqibsaeed** [comment]
Thank you.

**Comment by aqibsaeed** [comment]
Can I use it in Google Colab now? tff installation via pip package is also updated?

**Comment by ZacharyGarrett** [comment]
Sorry, the pip package has not been updated so this isn't usable in Google Colab yet. That will require a new release, and TFF typically release every few weeks. There maybe a release in the next few days, I'll check and follow-up.

**Comment by aqibsaeed** [comment]
Hey @ZacharyGarrett, 

Any updates about the release?

**Comment by ZacharyGarrett** [comment]
@aqibsaeed apologies for the delay, thanks for checking in. We we waiting to get a01eadc1b33b31947ec4540689a63e777c933205 merged (which is good to go now). Someone from the team will look at releasing a pip package today (though may take until tomorrow).

**Comment by aqibsaeed** [comment]
Thank you @ZacharyGarrett

**Comment by liuquande** [comment]
Hi @aqibsaeed , I met the same problem when I try to use multiple inputs in keras model. 
I am using tff 0.6.0 now. 
May I know how did you solve it and in which version is the problem fixed?

Many thanks!
