### ISSUE TITLE
support for keras callbacks (esp TensorBoard) during federated training

### ISSUE THREAD

**Issue by jpgard** [tensorflow/federated#787]
Currently, it does not seem that callbacks can be used during TFF model training -- for example, logging to a directory with ['tf.keras.callbacks.TensorBoard`](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard) for TensorBoard logging during training. More specifically, this is because callbacks are typically provided as parameters to the `mode.fit()` method, but TFF calls this function itself under the hood during federated training.

Having support for this would be hugely helpful for monitoring large-scale TFF experiments, e.g. for hyperparameter tuning. Of course, many of these metrics can be collected and logged manually in the case of TensorBoard (e.g. by writing metrics to a CSV as training progresses), but we lose access to the rich functionality of TensorBoard itself.

(apologies if this is actually implemented somewhere or available within the existing framework; if that is the case, please let me know!)

**Comment by ZacharyGarrett** [comment]
In the tutorials, there is a "round loop" for most federated learning computations. For example, in the text classification tutorial:

```python
for round_num in range(NUM_ROUNDS):
  state, metrics = fed_avg.next(state, train_datasets)
keras_evaluate(state, NUM_ROUNDS + 1)
```

The `metrics` object here can be used with `tf.summary` to get the _aggregated_ metrics into TensorBoard. For example:

```python
summary_writer = tf.summary.SummaryWriter(logdir='/tmp/logdir')

for round_num in range(NUM_ROUNDS):
  state, metrics = fed_avg.next(state, train_datasets)
  with summary_writer.as_default():
    for name, metric in metrics._asdict().items():
      tf.summary.scalar(name, metric)
keras_evaluate(state, NUM_ROUNDS + 1)
```

I'd posit there is some interesting work here to integrate better with Keras callbacks. Perhaps we could extend `tff.utils.IterativeProcess` or something around `tff.learning.build_federated_averaging_process` to allow specifying callbacks so that the workaround above wouldn't be necessary? This isn't well-formed thoughts yet though.

**Comment by jpgard** [comment]
Great, thanks @ZacharyGarrett .

For others who stumble on this, I was able to write training summary metrics via:

```
logdir = '/tmp/logdir'
summary_writer = tf.summary.create_file_writer(logdir)
for round_num in range(NUM_ROUNDS):
  state, metrics = fed_avg.next(state, train_datasets)
  with summary_writer.as_default():
    for name, metric in metrics._asdict().items():
      tf.summary.scalar(name, metric, round_num)
```
