### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by armanoj** [tensorflow/federated#796]
Hello,
I am trying to figure out how federated data looks and I am unable to find any resource where I can refer. So can you please let me know how the data actually looks. Even a small amount of data view will be helpful to understand(like mnist).
Thank you

**Comment by jkr26** [comment]
Hi @armanoj 

There are two distinct formats this data can be in, at the Python level--which you find more natural or easy to reason about tends to be background-dependent.

First, the recommended way for representing federated data is as a Python list of `tf.data.Datasets`, one dataset for each client. So that if you have a TFF computation whose `type_signature` attribute accepts `state` and federated data of type `{T*}@CLIENTS`, then a list of `tf.data.Datasets` whose `element_spec` attribute is of type `T` would fit the bill. Notice here the `T*` in the TFF type spec; this `*` represents a `tff.SequenceType`, which may be profitably thought of as a [stream](https://en.wikipedia.org/wiki/Stream_(computing)) of data on the device.

As a more concrete example, if you have a TFF model for MNIST which accepts batches of tensors of type `tf.float32` and shape `[batch_size, 784]` and makes predictions over integers, then you should be feeding in to your `next` function a list of datasets whose element spec is `(TensorSpec([None, 784], dtype=tf.float32), TensorSpec([None, 1], dtype=tf.int32)` (possibly allowing for names, or for the labels to be scalars instead of 1d vectors. I think a good reference for this is [here](https://www.tensorflow.org/federated/tutorials/federated_learning_for_image_classification#preparing_the_input_data) in the first TFF tutorial--it even prints out a sample batch.

The other way of representing federated data for TFF is as a list of list of numpy arrays. The outer list here represents the clients, and the inner list represents the data on a given client. While we don't tend to recommend this too much (as we would prefer standardizing on `tf.data.Datasets`), an example preparing such data that you may find helpful can be found [here](https://www.tensorflow.org/federated/tutorials/custom_federated_algorithms_2#preparing_federated_data_sets).
