### ISSUE TITLE
Loosen dependency on TFA

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/federated#799]
TensorFlow Addons is happy to be a part of the federated package. However, the current packaging restricts the version of TFA to be ~=0.6 which makes it so users can't keep an updated Addons library in their environment. 

This is especially problematic in Colab since TF-Federated is an installed package in the TF2.X environment. This means that by default a quite old version on TFA is installed and if the user tries to upgrade it will cause a dependency error with TF-Federated.

Would it be possible to pin to TFA >= 0.6 in your releases? There shouldn't be any breakage for the functionality that is being called within this repo.

Related: https://github.com/tensorflow/addons/issues/1104

**Comment by michaelreneer** [comment]
TFA has been broken in the past at latest release. I don't think it's generally a good idea to accept major/minor features in a release. This keeps a release of TFF stable, reproducible, and working. We do accept hot fixes, i.e. `tensorflow-addons~=0.7.0`.

See https://semver.org/ for more information.

**Comment by seanpmorgan** [comment]
Hi @michaelreneer thats fair and understand why its needed. I'll close this issue since I think it's more of an issue within colab environments, but I have little visibility into whats going on there. As of today it looks as though TFA was updated and TF==2.1.0 but TFF==0.11 which I didn't think was compatible with TF 2.1

![image](https://user-images.githubusercontent.com/18154355/74973259-1dc69a00-53f1-11ea-8f9c-9bef03bda3d4.png)

**Comment by michaelreneer** [comment]
@seanpmorgan I am also curious how the installation is being done.

FYI, we fixed an issue today that has allowed us to move our development dependencies to the latest version. I should be able to bump the version of TFA to latest release.

I 100% agree with you that the issue seems like a colab environment building issue. It seems like there should be some requirements.txt that define the colab environment and if a standard pip install fails you shouldn't accept a change to that requirements.txt.
