### ISSUE TITLE
tf_nightly-1.15.0.dev20190805

### ISSUE THREAD

**Issue by Zing22** [tensorflow/federated#802]
hello, I am looking for `tf_nightly-1.15.0.dev20190805` package on win64 platform. The link in README is not available. Could you please fix that link? thank you.

**Comment by michaelreneer** [comment]
@Zing22 thanks for bringing this to my attention, I'm taking a look at this.

**Comment by michaelreneer** [comment]
@Zing22 I have done some digging and the PyPI team has requested that TF delete old binary due to size limitations. See https://github.com/pypa/pypi-support/issues/224. As a result, these packages are no longer being distributed. Unfortunately, the TFF package was dependent on TF nightly package while code was being migrated from TF1 to TF2. This means that these versions of TFF are not easily pip installed.

I would recommend updating to the latest version of TFF, which does not have this issue.

**Comment by michaelreneer** [comment]
I have done some more digging and the exact requirements are...

- TFF `v0.9.0` -> tf-nightly
- TFF `v0.8.0` -> tf-nightly==1.15.0.dev20190805
- TFF `v0.7.0` -> tf-nightly
- TFF `v0.6.0` -> tf-nightly
- TFF `v0.5.0` -> tf-nightly

Therefore, `pip install tensorflow_federated==0.8.0` will fail. It's likely that the other TFF versions listed above will also fail (at run-time) because they will be pulling in the latest tf-nightly packages which use TF2 API.

Since `v0.10.0` we have specified out TF dependency against tensorflow fixing the major/minor version. Again, I am sorry that this is confusing and troublesome, this was done this way because of the transition from TF1 to TF2.
