### ISSUE TITLE
Bad Time Performance with  a lot of clients

### ISSUE THREAD

**Issue by steffenStra** [tensorflow/federated#804]
I am using the TF Federated Framework to implement a fare price predictor on the NYC taxi dataset. 
Therefore i split the dataset into a federated clientdataset and use it to train a federated predictor like in the tutorials provided online. 
I noticed that the time needed to train increases rapedly when the amount of clients is increased. 
All data is used for the training and is split across the amount of clients evenly.
With the same network type and same epochs it takes : 

1000 Clients , 500 Per Round : 130 minutes
100 Clients , 50     Per Round : 13 minutes
10 Clinets , 5        Per Round :  5 minutes

Is this something that happens normaly or is this some kind of bug ? Or am i doing something wrong here ? 

![Code](https://user-images.githubusercontent.com/62025839/76345905-70b2b380-6304-11ea-94a0-9c05de4b989a.PNG)

**Comment by michaelreneer** [comment]
Hi @steffenStra can I ask what version of TFF you are using?

**Comment by steffenStra** [comment]
Hi @michaelreneer i am using TFF Version 0.12.0 on google colab.

**Comment by michaelreneer** [comment]
Hi @steffenStra I think this seems normal, lets assume that your setup can run 20 clients in parallel, which takes about 5 minutes

10 clients: 1 batch (20 clients in parallel) = 5 minutes
50 clients: 2-3 batches of 20 clients in parallel * 5 minutes = 10-15 minutes
500 clients: ~25 batches of 20 clients in parallel * 5 minutes = 125 minutes

Also note that aggregation gets slower with more clients because this operation is serial, not parallel.

You might be able to take a look at creating a custom execution stack and adjusting the [max_fanout](https://www.tensorflow.org/federated/api_docs/python/tff/framework/local_executor_factory), which can be done with...

```python
executor_factory = tff.framework.local_executor_factory(
    num_clients=None,
    max_fanout=100,
    clients_per_thread=1)
tff.framework.set_default_executor(executor_factory)
```

However, you might want to take a look at setting up a [multi-machine simulation].(https://github.com/tensorflow/federated/blob/master/docs/tutorials/high_performance_simulation_with_kubernetes.ipynb)
