### ISSUE TITLE
To make federated data from a csv file

### ISSUE THREAD

**Issue by armanoj** [tensorflow/federated#848]
Hello,
actually i was working on movie recommendation system through federated learning, I have csv file called ratings, which has 3 columns userId, movieId and rating. Each user has given ratings to many movies. I want the federated version of this data, will you please elaborate how to do it if you have any idea. (I am stuck from 3 days xD)
Thank you

**Comment by ZacharyGarrett** [comment]
This is a question more about _how to use_ TFF, rather than an _issue_ or _bug_ with TFF.

For such questions, the [tensorflow-federated](https://stackoverflow.com/questions/tagged/tensorflow-federated) tag on [stackoverflow.com](http://www.stackoverflow.com) is a a better resource.

Possibly related posts on StackOverflow:

- [How to create federated dataset from a CSV file?](https://stackoverflow.com/questions/58965488/how-to-create-federated-dataset-from-a-csv-file)
- [TFF: How define tff.simulation.ClientData.from_clients_and_fn Function?](https://stackoverflow.com/questions/60265798/tff-how-define-tff-simulation-clientdata-from-clients-and-fn-function)
- [Federated learning : convert my own image dataset into tff simulation Clientdata](https://stackoverflow.com/questions/59741397/federated-learning-convert-my-own-image-dataset-into-tff-simulation-clientdata)
