### ISSUE TITLE
[Big Confusion] Can secure aggregation be supported by TF Federated? What about Homomorphic Encryption?

### ISSUE THREAD

**Issue by SamuelGong** [tensorflow/federated#855]
Hi there,

According to the paper [Practical secure aggregation for privacy-preserving machine learning](https://dl.acm.org/doi/pdf/10.1145/3133956.3133982), Google has proposed a secure aggregation scheme based in secret sharing. It seems to pretty fit the federated learning scenario so I am just wondering that has TF Federated already supported similar secure aggregation scheme or not?

According to my knowledge, we can somehow achieve secure-aggregation-based FL with Google's another library *TF Encrypted*, as what is shown in this [example](https://github.com/tf-encrypted/tf-encrypted/blob/master/examples/federated-learning/run.py). However, this project is not compatible with TF Federated, meaning that if I want to simulate secure aggregation with tensorflow, I have to construct many stuffs from scratch with TFE instead of reusing code in TFF.

Similar question is also asked for Homomorphic Encryption. Thanks for the attention!

**Comment by jkr26** [comment]
This is an active area of development for TFF, and has been the subject of some discussion between @jvmncs and @michaelreneer (that I don't really have full state on)--assigning Michael here.

**Comment by jvmncs** [comment]
Hi @SamuelGong, that secure aggregation in TFE was just an early how-to code example, and we've been working on a better solution since TFF was open-sourced. Last year, @mortendahl wrote [this RFC](https://github.com/tf-encrypted/rfcs/tree/master/20190924-tensorflow-federated) about integrating TFE with TFF.

More recently, we've been working on an initial implementation with support from @michaelreneer.  The design has changed a bit since the RFC and doesn't cover everything from there, but it should give you a good idea of our direction. We'll have more info to share about this soon. Thanks for your interest!

**Comment by SamuelGong** [comment]
Thanks for the reply. Looking for a better solution!
