### ISSUE TITLE
Custom Keras Model with TFF and Optimizers

### ISSUE THREAD

**Issue by aqibsaeed** [tensorflow/federated#924]
Hi,

I wanted to know is it possible to use custom keras model with TFF? I am not sure if the training behavior will be ok. I have this model:

```
 class CustomModel(tf.keras.Model):
  def train_step(self, data):
      x, y = data

      with tf.GradientTape() as tape:
          y_pred = self(x, training=True)
          loss = self.compiled_loss(y, y_pred, regularization_losses=self.losses)

      trainable_vars = self.trainable_variables
      gradients = tape.gradient(loss, trainable_vars)
      self.optimizer.apply_gradients(zip(gradients, trainable_vars))
      self.compiled_metrics.update_state(y, y_pred)
      return {m.name: m.result() for m in self.metrics}
```

```
def create_keras_model():
  inputs = tf.keras.Input(shape=(784,))
  outputs = tf.keras.layers.Dense(10, activation="softmax")(inputs)
  model = CustomModel(inputs, outputs)
  return model
```

```
def model_fn():
  keras_model = create_keras_model()
  return tff.learning.from_keras_model(
      keras_model,
      input_spec=preprocessed_example_dataset.element_spec,
      loss=tf.keras.losses.SparseCategoricalCrossentropy(),
      metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])
```

Another question is there are 2 optimizers:
```
iterative_process = tff.learning.build_federated_averaging_process(
    model_fn,
    client_optimizer_fn=lambda: tf.keras.optimizers.SGD(learning_rate=0.02),
    server_optimizer_fn=lambda: tf.keras.optimizers.SGD(learning_rate=1.0))
```
In the earlier versions of TFF there used to only one optimizer (on client). I read the Federated Learning paper, but did not understand why do we need to have an optimizer on server side. Could you please share some paper or relevant doc which provides information on this?

**Comment by ZacharyGarrett** [comment]
It looks like the code wants to a custom training loop for the "inner" (on client) optimizer. Rather than implement this inside the Model, implementing this inside the training `tff.templates.IterativeProcess` maybe more natural?

There is a simplified, flat view of a Federatd Averaging implementation in 
https://github.com/tensorflow/federated/tree/master/tensorflow_federated/python/examples/simple_fedavg

The client training loop is here: https://github.com/tensorflow/federated/blob/826b66f3f0964bc3dec14e30286b5412bfeffb64/tensorflow_federated/python/examples/simple_fedavg/simple_fedavg_tf.py#L192
It might be worth trying to fork that code and modify?

Side note on subclassed `tf.keras.Model`: they are not supported. This is because TFF requires being able to serialize all computation logic, as the code is intended to run on edge devices. Unfortunately, Keras' subclass models do not support this, from https://keras.io/guides/model_subclassing (which now seems to be 404) use to say: 

> However, in subclassed models, the model's topology is defined as Python code (rather than as a static graph of layers). That means the model's topology cannot be inspected or serialized. As a result, the following methods and attributes are not available for subclassed models:
>
> model.inputs and model.outputs. model.to_yaml() and model.to_json() model.get_config() and model.save().

https://keras.io/guides/making_new_layers_and_models_via_subclassing/

In general we recommend Keras' Functional API for models: https://keras.io/guides/functional_api/

**Comment by aqibsaeed** [comment]
Thanks @ZacharyGarrett  for the quick response. 

> "It looks like the code wants to a custom training loop for the "inner" (on client) optimizer. Rather than implement this inside the Model, implementing this inside the training tff.templates.IterativeProcess maybe more natural?"

It seems like TFF is going in the opposite direction of TF2.0 where it is highly marketed to override train_step function. I tested the code I posted earlier with [this TFF tutorial](https://www.tensorflow.org/federated/tutorials/federated_learning_for_image_classification) and it seems to be working fine and indeed I'm using a Keras' Functional API. 

Do you still recommend using [simple_fedavg](https://github.com/tensorflow/federated/tree/master/tensorflow_federated/python/examples/simple_fedavg)?
