### ISSUE TITLE
a problem of bazel

### ISSUE THREAD

**Issue by Chun78HunZi** [tensorflow/federated#929]
I use 'bazel run computation.proto'  command .But it doesn't generate 'computation_pb2' pyhton

**Comment by ZacharyGarrett** [comment]
For Bazel, I think this will want the `build` command (https://docs.bazel.build/versions/3.7.0/guide.html#build), rather than `run`. Bazel also desires the target label (`:computation_py_b2`), rather than the file name. More information about using Bazel can be found at https://docs.bazel.build/.

In this case, try:

```shell
$ bazel build tensorflow_federated/proto/v0:computation_py_pb2
```
